#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME
final_path=/opt/yunohost/$app

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop plexmediaserver service
systemctl stop plexmediaserver

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# Get the machine architecture
arch=$(uname -m)

# Check the architecture and set variable accordingly
if [ "$arch" = "x86_64" ]; then
  BUILD="linux-x86_64"
elif [ "$arch" = "i386" ]; then
  BUILD="linux-x86"
elif [ "$arch" = "aarch64" ]; then
  BUILD="linux-aarch64"
elif [ "$arch" = "armv7l" ]; then
  BUILD="linux-armv7neon"
else
    ynh_die "Your arch doesn't have a debian-compatible Plex release"
fi

# Fetch releases from Plex
PLEX_INDEX=$(curl -s https://plex.tv/pms/downloads/5.json);
SOURCE_URL=$(echo $PLEX_INDEX | jq -r ".computer.Linux.releases[]  | select(.distro == \"debian\" and .build == \"$BUILD\") | .url");
DEB_FILE="$final_path/plexmediaserver.deb";

ynh_script_progression --message="Downloading PlexMediaManager..."
ynh_app_setting_set "$app" final_path "$final_path"
mkdir -p "$final_path"
wget --tries 3 --no-dns-cache --timeout 900 --no-verbose --output-document=$DEB_FILE $SOURCE_URL 2>&1

# Verifying checksum
SOURCE_SUM=$(echo $PLEX_INDEX | jq -r ".computer.Linux.releases[]  | select(.distro == \"debian\" and .build == \"$BUILD\") | .checksum");
ACTUAL_SUM=$(sha1sum $DEB_FILE | cut -c 1-40)

if [ "$SOURCE_SUM" != "$ACTUAL_SUM" ]
then
  rm -f "$DEB_FILE"
  ynh_die --message="Download file have incorrect checksum. Aborting."
fi

#==============================================
# INSTALL PLEX
#==============================================

dpkg --install $DEB_FILE

#=================================================
# NGINX CONFIGURATION
#=================================================

# Create a dedicated nginx config
#ynh_add_nginx_config


#=================================================
# UPGRADE CONFIG
#=================================================
#cp -a ../conf/loolwsd.xml /etc/loolwsd
#ynh_replace_string "__NEXTCLOUDDOMAIN__" "$nextcloud_domain" "/etc/loolwsd/loolwsd.xml"
#ynh_replace_string "__PASSWORD__" "$password" "/etc/loolwsd/loolwsd.xml"
#systemctl restart loolwsd



# If app is public, add url to SSOWat conf as skipped_uris
#if [[ $is_public -eq 1 ]]; then
  # See install script
#  ynh_app_setting_set "$app" unprotected_uris "/"
#fi

# Start plexmediaserver service
systemctl start plexmediaserver
